import express from 'express';
import cors from 'cors';
import authRoutes from './routes/authRoutes.js';
import storeRoutes from './routes/storeRoutes.js';
import ratingRoutes from './routes/ratingRoutes.js';
import adminRoutes from './routes/adminRoutes.js';
import ownerRoutes from './routes/ownerRoutes.js';
import {env} from './config/env.js';
import {notFound,errorHandler} from './middleware/errorMiddleware.js';

const app=express();
app.disable('x-powered-by');
app.use(cors({origin:env.clientUrl,credentials:true}));
app.use(express.json({limit:'1mb'}));
app.get('/api/health',(req,res)=>res.json({success:true,message:'Rox_Web API is running'}));
app.use('/api/auth',authRoutes);
app.use('/api/stores',storeRoutes);
app.use('/api/ratings',ratingRoutes);
app.use('/api/admin',adminRoutes);
app.use('/api/owner',ownerRoutes);
app.use(notFound);
app.use(errorHandler);
export default app;