-- Run after schema.sql. Passwords are intentionally generated by the application/seed script;
-- replace the placeholder hashes below with bcrypt hashes for your local demo accounts.
INSERT INTO users (name,email,address,password_hash,role)
VALUES
('System Administrator Demo','admin@roxweb.local','Roxiler Admin Office','REPLACE_WITH_BCRYPT_HASH','ADMIN')
ON CONFLICT (email) DO NOTHING;

-- Store-owner and normal-user demo rows can be added after creating valid bcrypt hashes.