
import { useEffect, useState } from 'react';
import { Link, NavLink, Navigate, Route, Routes, useLocation, useNavigate } from 'react-router-dom';
import axios from 'axios';
import { ArrowUpDown, Building2, ChevronRight, Eye, KeyRound, LayoutDashboard, Search, Settings2, ShieldCheck, Star, Store, Trash2, UserRound, UsersRound } from 'lucide-react';

const api = axios.create({ baseURL: import.meta.env.VITE_API_URL || 'http://localhost:5000/api', timeout: 15000 });
api.interceptors.request.use(function (c) {
  const t = localStorage.getItem('rox_token');
  if (t) c.headers.Authorization = 'Bearer ' + t;
  return c;
});
api.interceptors.response.use(function (r) { return r; }, function (e) {
  if (e.response && e.response.status === 401) {
    const a = e.config && e.config.headers && e.config.headers.Authorization;
    const requestToken = a ? String(a).replace(/^Bearer\s+/i, '') : '';
    if (!requestToken || requestToken === localStorage.getItem('rox_token')) {
      localStorage.removeItem('rox_token'); localStorage.removeItem('rox_user');
    }
  }
  return Promise.reject(e);
});
const dataOf = function (r) { return r.data && r.data.data ? r.data.data : (r.data || {}); };
const errOf = function (e, fallback) { return (e.response && e.response.data && e.response.data.message) || fallback || 'Something went wrong.'; };

function useAuth() {
  const [user, setUser] = useState(function () {
    try { return JSON.parse(localStorage.getItem('rox_user') || 'null'); } catch { return null; }
  });
  const [loading, setLoading] = useState(!!localStorage.getItem('rox_token'));
  useEffect(function () {
    const token = localStorage.getItem('rox_token');
    if (!token) { setLoading(false); return; }
    let active = true;
    api.get('/auth/me').then(function (r) {
      if (!active) return;
      const u = dataOf(r).user; localStorage.setItem('rox_user', JSON.stringify(u)); setUser(u);
    }).catch(function () {
      if (!active) return;
      if (localStorage.getItem('rox_token') === token) { localStorage.removeItem('rox_token'); localStorage.removeItem('rox_user'); setUser(null); }
    }).finally(function () { if (active) setLoading(false); });
    return function () { active = false; };
  }, []);
  const login = async function (form) {
    const d = dataOf(await api.post('/auth/login', form));
    localStorage.setItem('rox_token', d.token); localStorage.setItem('rox_user', JSON.stringify(d.user)); setUser(d.user); return d.user;
  };
  const logout = function () { localStorage.removeItem('rox_token'); localStorage.removeItem('rox_user'); setUser(null); };
  return { user, loading, login, logout };
}

function Logo() { return <Link className="brand" to="/"><span className="brand-mark">R</span><span>Rox<span>Ratings</span></span></Link>; }
function Spinner() { return <span className="spinner" />; }
function Icon({name,size=16}) { const icons={dashboard:LayoutDashboard,users:UsersRound,user:UserRound,store:Store,stores:Building2,security:KeyRound,search:Search,sort:ArrowUpDown,view:Eye,delete:Trash2,star:Star,shield:ShieldCheck,settings:Settings2,arrow:ChevronRight}; const C=icons[name]||Star; return <C size={size} strokeWidth={1.9}/>; }
function Button(p) { return <button {...p} className={'btn ' + (p.variant || '') + ' ' + (p.className || '')}>{p.children}</button>; }
function Stars({ value, interactive, onChange }) { return <div className="stars">{[1,2,3,4,5].map(function (n) { return <button key={n} type="button" disabled={!interactive} className={n <= Number(value || 0) ? 'star active' : 'star'} onClick={function(){ if(onChange) onChange(n); }}>★</button>; })}</div>; }
function Field({ label, error, ...p }) { return <label className="field"><span>{label}</span><input {...p} className={'input ' + (error ? 'invalid' : '')}/>{error && <small className="field-error">{error}</small>}</label>; }
function Password({ label, value, onChange, error, placeholder }) { const [show,setShow]=useState(false); return <label className="field password-field"><span>{label}</span><input className={'input ' + (error ? 'invalid':'')} type={show?'text':'password'} value={value} onChange={onChange} placeholder={placeholder}/><button type="button" className="eye" onClick={()=>setShow(!show)}>{show?'●':'◉'}</button>{error&&<small className="field-error">{error}</small>}</label>; }
function Toast({ text, error, close }) { if(!text)return null; return <div className={'toast '+(error?'error':'')}><b>{error?'!':'✓'}</b><span>{text}</span><button onClick={close}>×</button></div>; }
function PageTitle({ eyebrow,title,description,action }) { return <div className="page-title"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1>{description&&<p>{description}</p>}</div>{action}</div>; }
function Loading(){return <div className="loading-block"><Spinner/> Loading live data…</div>;}
function Empty({title,text}){return <div className="empty"><div className="empty-icon"><Icon name="search" size={19}/></div><h3>{title}</h3><p>{text}</p></div>;}
function Stat({label,value,hint,icon}){return <div className="stat-card"><div className="stat-icon">{icon}</div><small>{label}</small><strong>{value}</strong><em>{hint}</em></div>;}

function AuthLayout({children}) {
  return <main className="auth-page"><div className="auth-wrap"><section className="auth-side"><Logo/><div className="auth-hero"><span className="hero-chip">TRUSTED STORE RATINGS</span><h1>Make every<br/><em>rating count.</em></h1><p>A polished workspace for customers, store owners and administrators, backed by real PostgreSQL data.</p><div className="hero-points"><span>✓ Live ratings</span><span>✓ Secure roles</span><span>✓ Real database</span></div></div></section><section className="auth-form"><div className="mobile-brand"><Logo/></div>{children}</section></div></main>;
}
function Login(){
  const a=useAuth(), nav=useNavigate(), loc=useLocation(), [f,setF]=useState({email:'',password:''}), [err,setErr]=useState(''), [busy,setBusy]=useState(false);
  if(a.loading)return <AuthLayout><Loading/></AuthLayout>;
  async function submit(e){e.preventDefault();setErr('');setBusy(true);try{const u=await a.login(f);nav(u.role==='ADMIN'?'/admin':u.role==='OWNER'?'/owner':'/stores',{replace:true});}catch(x){setErr(errOf(x,'Invalid email or password.'));}finally{setBusy(false);}}
  return <AuthLayout><form className="auth-card" onSubmit={submit}><div className="form-heading"><span className="mini-label">WELCOME BACK</span><h2>Sign in to your account</h2><p>Continue to your RoxRatings workspace.</p></div>{loc.state&&loc.state.message&&<div className="notice success">{loc.state.message}</div>}<Field label="Email" type="email" value={f.email} onChange={e=>setF({...f,email:e.target.value})} placeholder="you@example.com" required/><Password label="Password" value={f.password} onChange={e=>setF({...f,password:e.target.value})} placeholder="Enter your password"/>{err&&<div className="notice error">{err}</div>}<Button disabled={busy}>{busy?<><Spinner/> Signing in…</>:'Sign in →'}</Button><p className="auth-switch">New here? <Link to="/signup">Create an account</Link></p><p className="auth-footnote">Password reset is not exposed by the current API. Use Change Password after signing in.</p></form></AuthLayout>;
}
function Signup(){
  const nav=useNavigate(), [f,setF]=useState({name:'',email:'',address:'',password:''}), [errors,setErrors]=useState({}), [busy,setBusy]=useState(false);
  function set(k){return e=>setF({...f,[k]:e.target.value});}
  async function submit(e){e.preventDefault();const x={};if(f.name.trim().length<20||f.name.trim().length>60)x.name='Name must be 20–60 characters.';if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(f.email))x.email='Enter a valid email.';if(!/^(?=.*[A-Z])(?=.*[^A-Za-z0-9]).{8,16}$/.test(f.password))x.password='8–16 characters with uppercase + special character.';if(f.address.length>400)x.address='Address must be at most 400 characters.';setErrors(x);if(Object.keys(x).length)return;setBusy(true);try{await api.post('/auth/signup',f);nav('/login',{replace:true,state:{message:'Account created successfully. Please sign in.'}});}catch(e2){setErrors({form:errOf(e2,'Unable to create account.')});}finally{setBusy(false);}}
  return <AuthLayout><form className="auth-card wide" onSubmit={submit}><div className="form-heading"><span className="mini-label">GET STARTED</span><h2>Create your account</h2><p>Public registration creates a normal USER account.</p></div><Field label="Full name" value={f.name} onChange={set('name')} error={errors.name} placeholder="20–60 characters" required/><Field label="Email" type="email" value={f.email} onChange={set('email')} error={errors.email} placeholder="you@example.com" required/><Field label="Address" value={f.address} onChange={set('address')} error={errors.address} placeholder="Your address" required/><Password label="Password" value={f.password} onChange={set('password')} error={errors.password} placeholder="8–16 chars, uppercase + special"/>{errors.form&&<div className="notice error">{errors.form}</div>}<Button disabled={busy}>{busy?<><Spinner/> Creating…</>:'Create account →'}</Button><p className="auth-switch">Already registered? <Link to="/login">Sign in</Link></p></form></AuthLayout>;
}

const navs={USER:[['/stores','Discover stores','store'],['/user','My overview','dashboard'],['/user/password','Security','security']],OWNER:[['/owner','Owner overview','dashboard'],['/owner/password','Security','security']],ADMIN:[['/admin','Overview','dashboard'],['/admin/users','Users','users'],['/admin/stores','Stores','stores']]};
function Shell({kind,children}){
  const a=useAuth(), nav=useNavigate(), [open,setOpen]=useState(false);
  return <div className="app-shell"><header className="topbar"><Logo/><button className="menu-button" onClick={()=>setOpen(!open)}>☰</button><div className="top-user"><div className="avatar">{a.user&&a.user.name.slice(0,1).toUpperCase()}</div><div><strong>{a.user&&a.user.name}</strong><small>{a.user&&a.user.role}</small></div><button className="logout" onClick={()=>{a.logout();nav('/login')}}>Sign out</button></div></header><div className={'shell-body '+(open?'mobile-open':'')}><aside className="sidebar"><div className="side-label">{kind==='ADMIN'?'ADMIN CONSOLE':kind==='OWNER'?'STORE OWNER':'CUSTOMER'}</div>{navs[kind].map(function(n){return <NavLink key={n[0]} end={n[0]==='/admin'||n[0]==='/owner'||n[0]==='/user'} to={n[0]} onClick={()=>setOpen(false)} className={({isActive})=>isActive?'side-link active':'side-link'}><span className="nav-icon"><Icon name={n[2]} size={16}/></span>{n[1]}</NavLink>})}<div className="side-bottom"><div className="profile-mini"><div className="avatar">{a.user&&a.user.name.slice(0,1).toUpperCase()}</div><div><strong>{a.user&&a.user.name}</strong><small>{a.user&&a.user.email}</small></div></div></div></aside><main className="main-content">{children}</main></div></div>;
}
function Guard({roles,children}){const a=useAuth();if(a.loading)return <div className="center-page"><Loading/></div>;if(!a.user)return <Navigate to="/login" replace/>;if(roles&&!roles.includes(a.user.role))return <Navigate to={a.user.role==='ADMIN'?'/admin':a.user.role==='OWNER'?'/owner':'/stores'} replace/>;return children;}

function Stores(){
  const [rows,setRows]=useState([]),[q,setQ]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[toast,setToast]=useState('');
  async function load(){setLoading(true);try{setRows(dataOf(await api.get('/stores',{params:{search:q}})).stores||[]);setError('');}catch(e){setError(errOf(e));}finally{setLoading(false);}}
  useEffect(()=>{const t=setTimeout(load,220);return()=>clearTimeout(t);},[q]);
  async function rate(id,r){try{await api.post('/ratings',{storeId:id,rating:r});setToast('Rating saved.');load();}catch(e){setToast(errOf(e));}}
  return <Shell kind="USER"><Toast text={toast} error={toast!=='Rating saved.'&&!!toast} close={()=>setToast('')}/><PageTitle eyebrow="DISCOVER" title="Find a store" description="Search real stores and share a 1–5 star rating."/><div className="search-bar"><span><Icon name="search" size={17}/></span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search by store name or address…"/>{q&&<button onClick={()=>setQ('')}>×</button>}</div>{loading?<Loading/>:error?<div className="notice error">{error}</div>:rows.length===0?<Empty title="No stores found" text="Try a different name or address."/>:<div className="store-grid">{rows.map(function(s){return <article className="store-card" key={s.id}><div className="store-card-top"><div className="store-avatar large">{s.name.slice(0,1).toUpperCase()}</div><div><h3>{s.name}</h3><p>{s.address}</p></div></div><div className="rating-line"><div><div className="rating-number">{Number(s.averageRating||0).toFixed(1)}</div><Stars value={Math.round(Number(s.averageRating||0))}/></div><span>{s.ratingCount||0} ratings</span></div><div className="your-rating"><div><small>Your rating</small><Stars value={s.myRating||0} interactive onChange={r=>rate(s.id,r)}/></div>{s.myRating?<span className="rated-pill">Rated {s.myRating}/5</span>:<span className="rate-hint">Tap a star</span>}</div></article>})}</div>}</Shell>;
}
function UserHome(){
  const [rows,setRows]=useState([]);const[loading,setLoading]=useState(true);
  useEffect(()=>{api.get('/stores').then(r=>setRows(dataOf(r).stores||[])).finally(()=>setLoading(false));},[]);
  const rated=rows.filter(x=>x.myRating), avg=rated.length?(rated.reduce((a,x)=>a+x.myRating,0)/rated.length).toFixed(1):'—';
  return <Shell kind="USER"><PageTitle eyebrow="YOUR SPACE" title="My overview" description="A quick look at your real rating activity."/><div className="stats-grid"><Stat label="Stores available" value={rows.length} hint="Live from database" icon={<Icon name="store" size={18}/>}/><Stat label="Stores rated" value={rated.length} hint="Your submitted ratings" icon={<Icon name="star" size={18}/>}/><Stat label="Your average" value={avg} hint="Across your ratings" icon={<Icon name="star" size={18}/>}/></div><div className="content-grid two"><section className="panel"><div className="panel-head"><div><h2>Rated stores</h2><p>Your latest submitted ratings.</p></div><Link className="text-link" to="/stores">Browse stores →</Link></div>{loading?<Loading/>:rated.length===0?<Empty title="No ratings yet" text="Browse stores and leave your first rating."/>:<div className="activity-list">{rated.slice(0,6).map(s=><div className="activity-row" key={s.id}><div className="store-avatar">{s.name.slice(0,1).toUpperCase()}</div><div className="grow"><strong>{s.name}</strong><small>{s.address}</small></div><Stars value={s.myRating}/></div>)}</div>}</section><section className="panel insight"><span className="mini-label">YOUR VOICE</span><h2>Small feedback,<br/><em>real impact.</em></h2><p>Ratings help customers make better choices and give store owners useful feedback.</p><Link className="btn secondary" to="/stores">Explore stores</Link></section></div></Shell>;
}
function ChangePassword(){
  const a=useAuth(),[f,setF]=useState({currentPassword:'',newPassword:''}),[errors,setErrors]=useState({}),[toast,setToast]=useState(''),[busy,setBusy]=useState(false);
  async function submit(e){e.preventDefault();const x={};if(!f.currentPassword)x.currentPassword='Current password is required.';if(!/^(?=.*[A-Z])(?=.*[^A-Za-z0-9]).{8,16}$/.test(f.newPassword))x.newPassword='8–16 chars with uppercase + special character.';setErrors(x);if(Object.keys(x).length)return;setBusy(true);try{await api.post('/auth/change-password',f);setToast('Password updated successfully.');setF({currentPassword:'',newPassword:''});}catch(e2){setToast(errOf(e2));}finally{setBusy(false);}}
  return <Shell kind={a.user.role}><Toast text={toast} error={toast!=='Password updated successfully.'&&!!toast} close={()=>setToast('')}/><PageTitle eyebrow="ACCOUNT" title="Security" description="Update the password used to access your account."/><section className="panel form-panel"><div className="security-icon"><Icon name="security" size={20}/></div><h2>Change password</h2><p className="muted">Use 8–16 characters with at least one uppercase letter and one special character.</p><form onSubmit={submit} className="form-stack"><Password label="Current password" value={f.currentPassword} onChange={e=>setF({...f,currentPassword:e.target.value})} error={errors.currentPassword}/><Password label="New password" value={f.newPassword} onChange={e=>setF({...f,newPassword:e.target.value})} error={errors.newPassword}/><div className="form-actions"><Button disabled={busy}>{busy?'Updating…':'Update password'}</Button></div></form></section></Shell>;
}
function Owner(){
  const [d,setD]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
  useEffect(()=>{api.get('/owner/dashboard').then(r=>setD(dataOf(r))).catch(e=>setError(errOf(e))).finally(()=>setLoading(false));},[]);
  return <Shell kind="OWNER">{loading?<Loading/>:error?<div className="notice error">{error}</div>:!d.store?<Empty title="No store assigned" text="Ask an administrator to assign a store to your owner account."/>:<><PageTitle eyebrow="STORE OWNER" title="Owner overview" description={'Live performance for '+d.store.name+'.'}/><div className="stats-grid"><Stat label="Average rating" value={Number(d.averageRating||0).toFixed(1)} hint="Overall store score" icon="★"/><Stat label="Total ratings" value={d.totalRatings||0} hint="All submitted ratings" icon={<Icon name="star" size={18}/>}/><Stat label="Store" value={d.store.name} hint={d.store.address} icon="⌂"/></div><div className="content-grid two"><section className="panel"><div className="panel-head"><div><h2>Rating distribution</h2><p>How customers rated your store.</p></div></div><div className="distribution">{[5,4,3,2,1].map(function(n){const x=d.distribution&&d.distribution[n]?d.distribution[n]:{count:0,percentage:0};return <div className="dist-row" key={n}><span>{n} ★</span><div className="bar"><i style={{width:String(x.percentage)+'%'}}/></div><strong>{x.count}</strong><small>{x.percentage}%</small></div>})}</div></section><section className="panel profile-card"><div className="store-avatar large">{d.store.name.slice(0,1).toUpperCase()}</div><h3>{d.store.name}</h3><p>{d.store.address}</p><div className="big-score"><span>{Number(d.averageRating||0).toFixed(1)}</span><Stars value={Math.round(Number(d.averageRating||0))}/></div></section></div><section className="panel"><div className="panel-head"><div><h2>Customers who rated</h2><p>Real activity from your assigned store.</p></div></div>{!d.ratings||!d.ratings.length?<Empty title="No ratings yet" text="Customer ratings will appear here when submitted."/>:<div className="table-wrap"><table><thead><tr><th>Customer</th><th>Email</th><th>Rating</th><th>Updated</th></tr></thead><tbody>{d.ratings.map(r=><tr key={r.id}><td><strong>{r.user_name}</strong></td><td>{r.user_email}</td><td><Stars value={r.rating}/></td><td>{new Date(r.updated_at).toLocaleString()}</td></tr>)}</tbody></table></div>}</section></>}</Shell>;
}

function Modal({title,children,close}){return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className="modal"><div className="modal-head"><div><span className="mini-label">ADMIN ACTION</span><h2>{title}</h2></div><button onClick={close}>×</button></div>{children}</div></div>;}
function Admin(){
  const [s,setS]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
  useEffect(()=>{api.get('/admin/stats').then(r=>setS(dataOf(r))).catch(e=>setError(errOf(e))).finally(()=>setLoading(false));},[]);
  return <Shell kind="ADMIN"><PageTitle eyebrow="ADMIN CONSOLE" title="Overview" description="A live snapshot of your RoxRatings system."/><div className="stats-grid">{loading?<><div className="stat-card skeleton"/><div className="stat-card skeleton"/><div className="stat-card skeleton"/></>:error?<div className="notice error">{error}</div>:<><Stat label="Registered users" value={s.users} hint="All roles" icon={<Icon name="users" size={18}/>}/><Stat label="Stores" value={s.stores} hint="Active records" icon="⌂"/><Stat label="Ratings" value={s.ratings} hint="Submitted ratings" icon="★"/></>}</div><div className="content-grid two"><section className="panel insight dark"><span className="mini-label">SYSTEM HEALTH</span><h2>One place to manage<br/><em>your marketplace.</em></h2><p>Manage live PostgreSQL-backed users and stores from the sections below.</p></section><section className="panel"><div className="panel-head"><div><h2>Quick actions</h2><p>Jump directly into management.</p></div></div><div className="quick-grid"><Link className="quick" to="/admin/users"><span><Icon name="users" size={18}/></span><strong>Manage users</strong><small>Search, filter and edit</small></Link><Link className="quick" to="/admin/stores"><span><Icon name="stores" size={18}/></span><strong>Manage stores</strong><small>Create and assign owners</small></Link></div></section></div></Shell>;
}

function UserModal({item,close,saved}){
  const [f,setF]=useState({name:item?item.name:'',email:item?item.email:'',address:item?item.address:'',role:item?item.role:'USER',password:''}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  async function submit(e){e.preventDefault();setError('');if(f.name.trim().length<20||f.name.trim().length>60)return setError('Name must be 20–60 characters.');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(f.email))return setError('Enter a valid email.');if(f.password&&!/^(?=.*[A-Z])(?=.*[^A-Za-z0-9]).{8,16}$/.test(f.password))return setError('Password must be 8–16 chars with uppercase + special.');setBusy(true);try{if(item)await api.put('/admin/users/'+item.id,f);else await api.post('/admin/users',f);saved(item?'User updated.':'User created.');}catch(x){setError(errOf(x));}finally{setBusy(false);}}
  return <Modal title={item?'Edit user':'Add user'} close={close}><form className="form-stack" onSubmit={submit}><Field label="Full name" value={f.name} onChange={e=>setF({...f,name:e.target.value})} required/><Field label="Email" type="email" value={f.email} onChange={e=>setF({...f,email:e.target.value})} required/><Field label="Address" value={f.address} onChange={e=>setF({...f,address:e.target.value})}/><label className="field"><span>Role</span><select className="select full" value={f.role} onChange={e=>setF({...f,role:e.target.value})}><option>USER</option><option>OWNER</option><option>ADMIN</option></select></label><Password label={item?'New password (optional)':'Password'} value={f.password} onChange={e=>setF({...f,password:e.target.value})} placeholder="Leave blank to keep current"/>{error&&<div className="notice error">{error}</div>}<div className="form-actions"><Button type="button" variant="secondary" onClick={close}>Cancel</Button><Button disabled={busy}>{busy?'Saving…':item?'Save changes':'Create user'}</Button></div></form></Modal>;
}
function Users(){
  const [rows,setRows]=useState([]),[search,setSearch]=useState(''),[role,setRole]=useState(''),[sort,setSort]=useState('name'),[dir,setDir]=useState('asc'),[loading,setLoading]=useState(true),[modal,setModal]=useState(null),[toast,setToast]=useState('');
  async function load(){setLoading(true);try{setRows(dataOf(await api.get('/admin/users',{params:{search,role,sort,direction:dir}})).users||[])}finally{setLoading(false)}}
  useEffect(()=>{const t=setTimeout(load,200);return()=>clearTimeout(t)},[search,role,sort,dir]);
  async function del(u){if(!window.confirm('Delete '+u.name+'?'))return;try{await api.delete('/admin/users/'+u.id);setToast('User deleted.');load();}catch(e){setToast(errOf(e));}}
  return <Shell kind="ADMIN"><Toast text={toast} error={toast!=='User deleted.'&&!!toast} close={()=>setToast('')}/><PageTitle eyebrow="DIRECTORY" title="Users" description="Search, filter and manage every account." action={<Button onClick={()=>setModal('new')}>+ Add user</Button>}/><div className="toolbar panel compact"><div className="search-bar inline"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, email or address…"/></div><select className="select" value={role} onChange={e=>setRole(e.target.value)}><option value="">All roles</option><option>USER</option><option>OWNER</option><option>ADMIN</option></select><select className="select" value={sort} onChange={e=>setSort(e.target.value)}><option value="name">Sort: Name</option><option value="email">Sort: Email</option><option value="role">Sort: Role</option><option value="created_at">Sort: Created</option></select><button className="sort-btn" onClick={()=>setDir(dir==='asc'?'desc':'asc')}>{dir==='asc'?'↑':'↓'}</button></div><section className="panel">{loading?<Loading/>:rows.length===0?<Empty title="No users found" text="Try changing your filters."/>:<div className="table-wrap"><table><thead><tr><th>User</th><th>Email</th><th>Role</th><th>Rating</th><th>Joined</th><th></th></tr></thead><tbody>{rows.map(u=><tr key={u.id}><td><div className="table-person"><div className="avatar">{u.name.slice(0,1).toUpperCase()}</div><div><strong>{u.name}</strong><small>{u.address}</small></div></div></td><td>{u.email}</td><td><span className={'role '+u.role.toLowerCase()}>{u.role}</span></td><td>{u.role==='OWNER'?<div className="owner-rating-cell"><Stars value={Math.round(Number(u.owner_rating||0))}/><small>{u.owner_rating?Number(u.owner_rating).toFixed(1):'No ratings'} · {u.owner_rating_count||0}</small></div>:<span className="muted">—</span>}</td><td>{new Date(u.created_at).toLocaleDateString()}</td><td><div className="row-actions"><Link className="icon-btn" to={'/admin/users/'+u.id}>View</Link><button className="icon-btn" onClick={()=>setModal(u)}>Edit</button><button className="icon-btn danger-text" onClick={()=>del(u)}>Delete</button></div></td></tr>)}</tbody></table></div>}</section>{modal&&<UserModal item={modal==='new'?null:modal} close={()=>setModal(null)} saved={m=>{setModal(null);setToast(m);load()}}/>}</Shell>;
}
function UserDetails(){
  const id=useLocation().pathname.split('/').pop(),[u,setU]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
  useEffect(()=>{api.get('/admin/users/'+id).then(r=>setU(dataOf(r).user)).catch(e=>setError(errOf(e))).finally(()=>setLoading(false));},[id]);
  return <Shell kind="ADMIN"><PageTitle eyebrow="USER DETAILS" title={u?u.name:'User details'} description="Account information from the live database." action={<Link className="btn secondary" to="/admin/users">← Back</Link>}/>{loading?<Loading/>:error?<div className="notice error">{error}</div>:<div className="detail-grid"><section className="panel profile-detail"><div className="avatar huge">{u.name.slice(0,1).toUpperCase()}</div><span className={'role '+u.role.toLowerCase()}>{u.role}</span><h2>{u.name}</h2><p>{u.email}</p><p>{u.address||'No address provided.'}</p></section><section className="panel"><h2>Account metadata</h2><div className="meta-list"><div><span>User ID</span><strong>#{u.id}</strong></div><div><span>Joined</span><strong>{new Date(u.created_at).toLocaleString()}</strong></div><div><span>Role</span><strong>{u.role}</strong></div>{u.role==='OWNER'&&<><div><span>Assigned store</span><strong>{u.owner_store_name||'No store assigned'}</strong></div><div><span>Store rating</span><strong>{u.owner_store_id?<span className="detail-rating"><Stars value={Math.round(Number(u.owner_rating||0))}/>{u.owner_rating?Number(u.owner_rating).toFixed(1):'No ratings yet'}</span>:'—'}</strong></div><div><span>Total ratings</span><strong>{u.owner_store_id?(u.owner_rating_count||0):'—'}</strong></div></>}</div></section></div>}</Shell>;
}
function StoreModal({item,owners,close,saved}){
  const [f,setF]=useState({name:item?item.name:'',email:item?item.email||'':'',address:item?item.address:'',ownerId:item&&item.owner_id?item.owner_id:''}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  async function submit(e){e.preventDefault();setError('');if(!f.name.trim())return setError('Store name is required.');if(f.address.length>400)return setError('Address must be at most 400 characters.');setBusy(true);try{const body={...f,ownerId:f.ownerId?Number(f.ownerId):null};if(item)await api.put('/admin/stores/'+item.id,body);else await api.post('/admin/stores',body);saved(item?'Store updated.':'Store created.');}catch(x){setError(errOf(x));}finally{setBusy(false);}}
  return <Modal title={item?'Edit store':'Add store'} close={close}><form className="form-stack" onSubmit={submit}><Field label="Store name" value={f.name} onChange={e=>setF({...f,name:e.target.value})} required/><Field label="Email" type="email" value={f.email} onChange={e=>setF({...f,email:e.target.value})}/><Field label="Address" value={f.address} onChange={e=>setF({...f,address:e.target.value})} required/><label className="field"><span>Assign owner</span><select className="select full" value={f.ownerId} onChange={e=>setF({...f,ownerId:e.target.value})}><option value="">Unassigned</option>{owners.map(o=><option key={o.id} value={o.id}>{o.name} — {o.email}</option>)}</select></label>{error&&<div className="notice error">{error}</div>}<div className="form-actions"><Button type="button" variant="secondary" onClick={close}>Cancel</Button><Button disabled={busy}>{busy?'Saving…':item?'Save changes':'Create store'}</Button></div></form></Modal>;
}
function StoresAdmin(){
  const [rows,setRows]=useState([]),[owners,setOwners]=useState([]),[q,setQ]=useState(''),[sort,setSort]=useState('name'),[dir,setDir]=useState('asc'),[loading,setLoading]=useState(true),[modal,setModal]=useState(null),[toast,setToast]=useState('');
  async function load(){setLoading(true);try{const [a,b]=await Promise.all([api.get('/admin/stores',{params:{search:q,sort,direction:dir}}),api.get('/admin/users',{params:{role:'OWNER'}})]);setRows(dataOf(a).stores||[]);setOwners(dataOf(b).users||[])}finally{setLoading(false)}}
  useEffect(()=>{const t=setTimeout(load,200);return()=>clearTimeout(t)},[q,sort,dir]);
  async function del(s){if(!window.confirm('Delete '+s.name+'?'))return;try{await api.delete('/admin/stores/'+s.id);setToast('Store deleted.');load();}catch(e){setToast(errOf(e));}}
  return <Shell kind="ADMIN"><Toast text={toast} error={toast!=='Store deleted.'&&!!toast} close={()=>setToast('')}/><PageTitle eyebrow="MARKETPLACE" title="Stores" description="Manage store records, owners and rating summaries." action={<Button onClick={()=>setModal('new')}>+ Add store</Button>}/><div className="toolbar panel compact"><div className="search-bar inline"><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search name, email or address…"/></div><select className="select" value={sort} onChange={e=>setSort(e.target.value)}><option value="name">Sort: Name</option><option value="email">Sort: Email</option><option value="address">Sort: Address</option><option value="rating">Sort: Rating</option></select><button className="sort-btn" onClick={()=>setDir(dir==='asc'?'desc':'asc')}>{dir==='asc'?'↑':'↓'}</button></div><section className="panel">{loading?<Loading/>:rows.length===0?<Empty title="No stores found" text="Create the first store to get started."/>:<div className="table-wrap"><table><thead><tr><th>Store</th><th>Owner</th><th>Rating</th><th>Email</th><th></th></tr></thead><tbody>{rows.map(s=><tr key={s.id}><td><div className="table-person"><div className="store-avatar">{s.name.slice(0,1).toUpperCase()}</div><div><strong>{s.name}</strong><small>{s.address}</small></div></div></td><td>{s.owner_name||<span className="muted">Unassigned</span>}</td><td><strong>{Number(s.average_rating||0).toFixed(1)}</strong><small className="table-sub">{s.rating_count} ratings</small></td><td>{s.email||'—'}</td><td><div className="row-actions"><button className="icon-btn" onClick={()=>setModal(s)}>Edit</button><button className="icon-btn danger-text" onClick={()=>del(s)}>Delete</button></div></td></tr>)}</tbody></table></div>}</section>{modal&&<StoreModal item={modal==='new'?null:modal} owners={owners} close={()=>setModal(null)} saved={m=>{setModal(null);setToast(m);load()}}/>}</Shell>;
}
function Home(){const a=useAuth();if(a.loading)return <div className="center-page"><Loading/></div>;if(!a.user)return <Navigate to="/login" replace/>;return <Navigate to={a.user.role==='ADMIN'?'/admin':a.user.role==='OWNER'?'/owner':'/stores'} replace/>;}

export default function App(){return <Routes><Route path="/login" element={<Login/>}/><Route path="/signup" element={<Signup/>}/><Route path="/" element={<Home/>}/><Route path="/stores" element={<Guard roles={['USER']}><Stores/></Guard>}/><Route path="/user" element={<Guard roles={['USER']}><UserHome/></Guard>}/><Route path="/user/password" element={<Guard roles={['USER']}><ChangePassword/></Guard>}/><Route path="/owner" element={<Guard roles={['OWNER']}><Owner/></Guard>}/><Route path="/owner/password" element={<Guard roles={['OWNER']}><ChangePassword/></Guard>}/><Route path="/admin" element={<Guard roles={['ADMIN']}><Admin/></Guard>}/><Route path="/admin/users" element={<Guard roles={['ADMIN']}><Users/></Guard>}/><Route path="/admin/users/:id" element={<Guard roles={['ADMIN']}><UserDetails/></Guard>}/><Route path="/admin/stores" element={<Guard roles={['ADMIN']}><StoresAdmin/></Guard>}/><Route path="*" element={<Home/>}/></Routes>;}
